"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from nest_api.types import BaseModel
from nest_api.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetUserRequestTypedDict(TypedDict):
    login: str


class GetUserRequest(BaseModel):
    login: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
