"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from nest_api.models import APIError
from nest_api.types import BaseModel
from typing import Optional


class UserErrorResponseData(BaseModel):
    detail: str


class UserErrorResponse(APIError):
    data: UserErrorResponseData

    def __init__(
        self,
        data: UserErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
