workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    owasp-nest-openapi:
        inputs:
            - location:  https://3852c590f368.ngrok-free.app/api/v1/openapi.json
        transformations:
            - removeUnused: true
        registry:
            location: registry.speakeasyapi.dev/owasp/nest/python-sdk
targets:
    nest-api:
        target: python
        source: owasp-nest-openapi
        output: .
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/owasp/nest/owasp-nest-api-python-code-samples
            blocking: false
